version: '3'
services:
  httpd:
    container_name: httpd-container
    build: ./apache
    ports:
      - "80:80"
    stdin_open: true
    # 権限の有効化
    privileged: true
  tomcat1:
    container_name: tomcat-container1
    build: ./tomcat
    expose:
      - "8009"