##################################################
# ECRにpushする用のdocker-compose
# 「image」の値を修正後、下記コマンドを実行。
#
# ※environment, exposeが効かないためDockerfileに定義している。
# 上記都合により、参照しているDockerfileがローカル用のdocker-composeと異なる。
# 
# ■build
# docker-compose -f docker-compose_pro.yml build
#
# ■push
# docker-compose -f docker-compose_pro.yml push
##################################################

version: '2'
services:
  db:
    image: 249758602895.dkr.ecr.ap-northeast-1.amazonaws.com/test:latest
    build: 
      # Dockerfileのビルド時の起点を設定
      context: .
      dockerfile: ./docker4ecs/db/Dockerfile
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: BOOK_DB
#      TZ: Asia/Tokyo
#    ports:
#      - "3306:3306"
  httpd:
    image: 249758602895.dkr.ecr.ap-northeast-1.amazonaws.com/apache:latest
    container_name: httpd-container
    build: 
      # Dockerfileのビルド時の起点を設定
      context: .
      dockerfile: ./docker4ecs/web_app/apache/Dockerfile
#    ports:
#      - "80:80"
    stdin_open: true
    # 権限の有効化
    privileged: true
  tomcat1:
    image: 249758602895.dkr.ecr.ap-northeast-1.amazonaws.com/tomcat:latest
    container_name: tomcat-container1
    build: 
      # Dockerfileのビルド時の起点を設定
      context: .
      dockerfile: ./docker4ecs/web_app/tomcat/Dockerfile
#    expose:
#      - "8009"