# バージョン指定（固定）
AWSTemplateFormatVersion: 2010-09-09
# テンプレートを説明する文字列（必須（必ずAWSTemplateFormatVersion直下に記載する））
Description: Create ECR

###############################################
# 作成するリソースを定義
###############################################
Resources:
  # MySQLイメージを格納するリポジトリ
  DBRepository:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: test
  # Apacheイメージを格納するリポジトリ
  ApacheRepository:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: apache
  # Tomcatイメージを格納するリポジトリ
  TomcatRepository:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: tomcat