##################################################
# ■コンテナ起動コマンド
# docker-compose up -d
#
# ■起動したコンテナに入るコマンド
# docker exec -it [コンテナ名/コンテナID] /bin/bash
#
# ■DBに入るコマンド
# mysql -u root -p
# enter押下後、rootのパスワードを入力
##################################################

version: '2'
services:
  db:
    build: ./db/
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: BOOK_DB
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
  httpd:
    container_name: httpd-container
    build: ./web_app/apache
    ports:
      - "80:80"
    stdin_open: true
    # 権限の有効化
    privileged: true
  tomcat1:
    container_name: tomcat-container1
    build: ./web_app/tomcat
    expose:
      - "8009"